# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7ec39b2870c95c2954cf2049763b0848"
name = "discount-manager"
application_url = "https://shopify-discount-manager.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mb2bstr.myshopify.com"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_locations,read_orders,read_shipping,write_discounts,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://shopify-discount-manager.vercel.app/auth/callback",
  "https://shopify-discount-manager.vercel.app/auth/shopify/callback",
  "https://shopify-discount-manager.vercel.app/api/auth/callback"
]
